# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
 name = "Posts"
 url = "#posts"
 weight = 20

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

#[[main]]
#  name = "Awards"
#  url = "#accomplishments"
#  weight = 40


[[main]]
  name = "Publications"
<<<<<<< HEAD
  url = "publication"
=======
  url = "#Publications"
>>>>>>> aad42bd540734b2e7992a5fca9cb0ce3b1ba3af7
  weight = 50
[[main]]
  name = "Covers"
  url = "#covers"
  weight = 60

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70

[[main]]
  name = "Featured Publications"
  url = "#featured"
  weight = 40
 
# [[main]]
#  name = "Team"
#  url = "#featured"
#  weight = 80
  
  [[main]]
  name = "Team"
  url = "#people"
  weight = 90
  
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 [[main]]
    name = "CV"
    url = "files/cv.pdf"
    weight = 100
